server:
  port: 8083
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:*.xml
    type-aliases-package: com.example.model,com.example.mapper